.gitignore, cogs/P143_jyanken.py
題名の通りです。
・出した手をテキストではなく絵文字に
・関係ない絵文字でループしないように
=> jyankencogの改良

bot.py, cogs/m10s_info.py, cogs/m10s_other.py
・dguildコマンドが動作しない不具合の修正
・feedback/reportコマンドの送信先の変更
・無効なリンクのパートナーサーバーのリンク更新
・helpコマンドの検索時にエラーをはく問題の修正
p.s.実際動作環境に反映済みです。
=> いくつかの不具合修正と仕様変更

bot.py, cogs/m10s_info.py, cogs/nekok500_mee6.py
ctx.send()に対してcolorのキーワード引数を指定していた問題を修正
=> levelsコマンドのバグ修正

bot.py, cogs/m10s_info.py
1.3.0対応のために以下のことを行いました
・カスタムステータス使用部の更新
・inviteイベントのログ化の追加(コード上は)
・その他いくつかの変更
=> カスタムステータスの絵文字表示

bot.py, cogs/m10s_info.py, cogs/m10s_other.py, lang/ja.json, m10s_util.py
=> 他言語対応部分の増加

cogs/pf9_symmetry.py
題名の通り。
#内容
・ループしないように修正
・シンメトリーにするサイドを指定できるように
=> symmetryコマンドの改良

cogs/m10s_other.py
botinfoコマンドにメモリの使用量などを表示するようにしました。
また、再起動コマンドを作成しました。
=> ボットの情報部分にメモリ情報の追加

cogs/m10s_other.py
=> Remove reboot command

bot.py, cogs/apple_foc.py, cogs/apple_invite.py, cogs/apple_misc.py, data/programming_info/javascript.json, data/programming_info/python.json
This adds coding feature. The code is hardcoded but maybe we can do something later?
=> Add Coding feature

bot.py, cogs/_template.py, cogs/apple_misc.py, cogs/m10s_games.py, cogs/m10s_gcoms.py, cogs/m10s_info.py, cogs/m10s_levels.py, cogs/m10s_manage.py, cogs/m10s_other.py, cogs/m10s_owner.py, cogs/m10s_search.py, cogs/m10s_settings.py, cogs/m10s_tests.py, cogs/nekok500_mee6.py, l10n.py
This is a big change, review carefully
=> textto() rework

cogs/m10s_music.py
=> 音楽Cog:対応ソースの拡大や退出時の不具合修正

.github/workflows/check_syntax.yml, requirements.txt
githubアクションを使いpushした時に構文チェックしてくれるものを追加
=> push時のflake8によるチェック

.gitignore, cogs/m10s_info.py
Guild.featuresのcommunityへの変更に対応
=> コミュニティサーバーfeaturesへの対応の更新

bot.py, cogs/m10s_info.py, cogs/m10s_owner.py, cogs/m10s_search.py, lang/ja.json
今までの
config.py内に記述するパートナーサーバーからデータベースファイルに保管する方式に変更
伴っていくつかの機能削除
=> 思惟奈ちゃんの認証済みサーバーに関する変更

cogs/m10s_music.py, m10s_util.py
・Discord Partner → Partnered Server Owner
・音楽Cogの不具合修正
=> バッジ名変更と不具合修正

bot.py
ユーザープロファイル作成時、DMへのメッセージ送信からメッセージ送信チャンネルへのメッセージ送信への変更。
=> ユーザープロファイル作成時の挙動の変更

bot.py, cogs/m10s_gcoms.py
titleの通りの機能を追加した…。と思います(動作確認さぼった(え
=> グローバルチャットでの返信投稿対応

bot.py, cogs/m10s_owner.py
titleのものに加えて、inserverコマンドでの思惟奈ちゃんの参加時刻がおかしかった問題の修正も行っています。
=> プレイ中テキストの一部置き換え、サーバー退出時のサーバー詳細情報表示の追加など

bot.py, cogs/_m10s_beta.py, cogs/_m10s_music_slash.py, cogs/_m10s_slash_testing.py, cogs/m10s_auth_wiz.py, cogs/m10s_chinfo_rewrite.py, cogs/m10s_gcoms.py, cogs/m10s_info.py, cogs/m10s_levels.py, cogs/m10s_music.py, cogs/m10s_re_gchat.py, cogs/m10s_role_panel.py, lang/ja.json, m10s_util.py
=> 現在実行環境とGit上のソースコードの同期

bot.py, cogs/P143_jyanken.py, requirements.txt
#56 を見かけたので。
Embedの色の指定と、返信パターンの追加、リアクションからviewへの変更を行っています。
(+ 環境構築のため、requirements.txtを一部改善)
=> jyankenCogを改善 (#56)

.github/workflows/check_syntax.yml, bot.py, cogs/P143_jyanken.py
フルログ表示に関しては削除されたissueですが。
デバッグがよりやりやすくなると思います。
=> チェックが動作しない問題の改善・フルログ表示

bot.py
=> エラーログがリストになってしまう問題を修正

bot.py, cogs/P143_jyanken.py, cogs/_template.py, cogs/apple_invite.py, cogs/apple_misc.py, cogs/apple_onlinenotif.py, cogs/hybrid/info_check.py, cogs/hybrid/m10s_help.py, cogs/hybrid/m10s_levels.py, cogs/hybrid/m10s_music.py, cogs/hybrid/m10s_quick_cmd.py, cogs/hybrid/m10s_re_gchat.py, cogs/m10s_app_metadata.py, cogs/m10s_auth_wiz.py, cogs/m10s_bmail.py, cogs/m10s_games.py, cogs/m10s_info.py, cogs/m10s_manage.py, cogs/m10s_other.py, cogs/m10s_partners.py, cogs/m10s_remainder.py, cogs/m10s_role_panel.py, cogs/m10s_search.py, cogs/m10s_set_activity_roles.py, cogs/m10s_settings.py, cogs/nekok500_mee6.py, cogs/pf9_symmetry.py, cogs/syouma.py, m10s_util.py
スラッシュコマンド向けパーミッション確認デコレータの追加。
comlockの確認デコレータの、スラッシュコマンド対応版を追加。
settingsのコマンドで、権限確認なしに一部サーバー設定を書き換えることができる問題を修正
チーム☆思惟奈ちゃんメンバーを除き、コマンド使用方法をスラッシュコマンドに完全移行できるコードを追加。
=> 権限をバイパスできてしまう不具合への対応

bot.py, cogs/hybrid/m10s_music.py, cogs/hybrid/m10s_re_gchat.py
メッセージ一括削除の実装
個人ごとに、利用前に規約同意を必須にする変更
=> グローバルチャットに関する改善etc

bot.py
=> サーバーカスタムコマンド時のprefix問題を修正

cogs/m10s_other.py
ロールへのメンションの荒らし行為に悪用された事例の発生による対応
=> メモコマンドの応答を一時メッセージに変更

m10s_util.py
Potential fix for [https://github.com/SinaKitagami/program-team/security/code-scanning/696](https://github.com/SinaKitagami/program-team/security/code-scanning/696)
To fix the issue, we need to ensure that `mvc` is always initialized before it is used. The best approach is to initialize `mvc` to a default value (e.g., `None`) at the start of the function. This ensures that `mvc` is defined regardless of whether the `try` block executes successfully. Additionally, we should add a check to ensure that `mvc` is not `None` before accessing its attributes.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Potential fix for code scanning alert no. 696: Potentially uninitialized local variable
